// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Xbox : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean A
        {
            get
            {
                return SteamVR_Actions.xbox_A;
            }
        }
        
        public virtual SteamVR_Action_Boolean B
        {
            get
            {
                return SteamVR_Actions.xbox_B;
            }
        }
        
        public virtual SteamVR_Action_Boolean Y
        {
            get
            {
                return SteamVR_Actions.xbox_Y;
            }
        }
        
        public virtual SteamVR_Action_Boolean X
        {
            get
            {
                return SteamVR_Actions.xbox_X;
            }
        }
        
        public virtual SteamVR_Action_Boolean Start
        {
            get
            {
                return SteamVR_Actions.xbox_Start;
            }
        }
        
        public virtual SteamVR_Action_Boolean Select
        {
            get
            {
                return SteamVR_Actions.xbox_Select;
            }
        }
        
        public virtual SteamVR_Action_Boolean DUp
        {
            get
            {
                return SteamVR_Actions.xbox_DUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean DDown
        {
            get
            {
                return SteamVR_Actions.xbox_DDown;
            }
        }
        
        public virtual SteamVR_Action_Boolean DLeft
        {
            get
            {
                return SteamVR_Actions.xbox_DLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean DRight
        {
            get
            {
                return SteamVR_Actions.xbox_DRight;
            }
        }
        
        public virtual SteamVR_Action_Vector2 DPad
        {
            get
            {
                return SteamVR_Actions.xbox_DPad;
            }
        }
        
        public virtual SteamVR_Action_Vector2 StickLeft
        {
            get
            {
                return SteamVR_Actions.xbox_StickLeft;
            }
        }
        
        public virtual SteamVR_Action_Vector2 StickRight
        {
            get
            {
                return SteamVR_Actions.xbox_StickRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean LB
        {
            get
            {
                return SteamVR_Actions.xbox_LB;
            }
        }
        
        public virtual SteamVR_Action_Boolean RB
        {
            get
            {
                return SteamVR_Actions.xbox_RB;
            }
        }
        
        public virtual SteamVR_Action_Single LT
        {
            get
            {
                return SteamVR_Actions.xbox_LT;
            }
        }
        
        public virtual SteamVR_Action_Single RT
        {
            get
            {
                return SteamVR_Actions.xbox_RT;
            }
        }
        
        public virtual SteamVR_Action_Boolean StickLeftClick
        {
            get
            {
                return SteamVR_Actions.xbox_StickLeftClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean StickRightClick
        {
            get
            {
                return SteamVR_Actions.xbox_StickRightClick;
            }
        }
        
        public virtual SteamVR_Action_Vibration Vibration
        {
            get
            {
                return SteamVR_Actions.xbox_Vibration;
            }
        }
    }
}
