// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Boolean p_xbox_A;
        
        private static SteamVR_Action_Boolean p_xbox_B;
        
        private static SteamVR_Action_Boolean p_xbox_Y;
        
        private static SteamVR_Action_Boolean p_xbox_X;
        
        private static SteamVR_Action_Boolean p_xbox_Start;
        
        private static SteamVR_Action_Boolean p_xbox_Select;
        
        private static SteamVR_Action_Boolean p_xbox_DUp;
        
        private static SteamVR_Action_Boolean p_xbox_DDown;
        
        private static SteamVR_Action_Boolean p_xbox_DLeft;
        
        private static SteamVR_Action_Boolean p_xbox_DRight;
        
        private static SteamVR_Action_Vector2 p_xbox_DPad;
        
        private static SteamVR_Action_Vector2 p_xbox_StickLeft;
        
        private static SteamVR_Action_Vector2 p_xbox_StickRight;
        
        private static SteamVR_Action_Boolean p_xbox_LB;
        
        private static SteamVR_Action_Boolean p_xbox_RB;
        
        private static SteamVR_Action_Single p_xbox_LT;
        
        private static SteamVR_Action_Single p_xbox_RT;
        
        private static SteamVR_Action_Boolean p_xbox_StickLeftClick;
        
        private static SteamVR_Action_Boolean p_xbox_StickRightClick;
        
        private static SteamVR_Action_Vibration p_xbox_Vibration;
        
        public static SteamVR_Action_Boolean xbox_A
        {
            get
            {
                return SteamVR_Actions.p_xbox_A.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean xbox_B
        {
            get
            {
                return SteamVR_Actions.p_xbox_B.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean xbox_Y
        {
            get
            {
                return SteamVR_Actions.p_xbox_Y.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean xbox_X
        {
            get
            {
                return SteamVR_Actions.p_xbox_X.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean xbox_Start
        {
            get
            {
                return SteamVR_Actions.p_xbox_Start.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean xbox_Select
        {
            get
            {
                return SteamVR_Actions.p_xbox_Select.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean xbox_DUp
        {
            get
            {
                return SteamVR_Actions.p_xbox_DUp.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean xbox_DDown
        {
            get
            {
                return SteamVR_Actions.p_xbox_DDown.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean xbox_DLeft
        {
            get
            {
                return SteamVR_Actions.p_xbox_DLeft.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean xbox_DRight
        {
            get
            {
                return SteamVR_Actions.p_xbox_DRight.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 xbox_DPad
        {
            get
            {
                return SteamVR_Actions.p_xbox_DPad.GetCopy <SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Vector2 xbox_StickLeft
        {
            get
            {
                return SteamVR_Actions.p_xbox_StickLeft.GetCopy <SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Vector2 xbox_StickRight
        {
            get
            {
                return SteamVR_Actions.p_xbox_StickRight.GetCopy <SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean xbox_LB
        {
            get
            {
                return SteamVR_Actions.p_xbox_LB.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean xbox_RB
        {
            get
            {
                return SteamVR_Actions.p_xbox_RB.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Single xbox_LT
        {
            get
            {
                return SteamVR_Actions.p_xbox_LT.GetCopy <SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Single xbox_RT
        {
            get
            {
                return SteamVR_Actions.p_xbox_RT.GetCopy <SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean xbox_StickLeftClick
        {
            get
            {
                return SteamVR_Actions.p_xbox_StickLeftClick.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean xbox_StickRightClick
        {
            get
            {
                return SteamVR_Actions.p_xbox_StickRightClick.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vibration xbox_Vibration
        {
            get
            {
                return SteamVR_Actions.p_xbox_Vibration.GetCopy <SteamVR_Action_Vibration>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[]
            {
                    SteamVR_Actions.xbox_A,
                    SteamVR_Actions.xbox_B,
                    SteamVR_Actions.xbox_Y,
                    SteamVR_Actions.xbox_X,
                    SteamVR_Actions.xbox_Start,
                    SteamVR_Actions.xbox_Select,
                    SteamVR_Actions.xbox_DUp,
                    SteamVR_Actions.xbox_DDown,
                    SteamVR_Actions.xbox_DLeft,
                    SteamVR_Actions.xbox_DRight,
                    SteamVR_Actions.xbox_DPad,
                    SteamVR_Actions.xbox_StickLeft,
                    SteamVR_Actions.xbox_StickRight,
                    SteamVR_Actions.xbox_LB,
                    SteamVR_Actions.xbox_RB,
                    SteamVR_Actions.xbox_LT,
                    SteamVR_Actions.xbox_RT,
                    SteamVR_Actions.xbox_StickLeftClick,
                    SteamVR_Actions.xbox_StickRightClick,
                    SteamVR_Actions.xbox_Vibration};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[]
            {
                    SteamVR_Actions.xbox_A,
                    SteamVR_Actions.xbox_B,
                    SteamVR_Actions.xbox_Y,
                    SteamVR_Actions.xbox_X,
                    SteamVR_Actions.xbox_Start,
                    SteamVR_Actions.xbox_Select,
                    SteamVR_Actions.xbox_DUp,
                    SteamVR_Actions.xbox_DDown,
                    SteamVR_Actions.xbox_DLeft,
                    SteamVR_Actions.xbox_DRight,
                    SteamVR_Actions.xbox_DPad,
                    SteamVR_Actions.xbox_StickLeft,
                    SteamVR_Actions.xbox_StickRight,
                    SteamVR_Actions.xbox_LB,
                    SteamVR_Actions.xbox_RB,
                    SteamVR_Actions.xbox_LT,
                    SteamVR_Actions.xbox_RT,
                    SteamVR_Actions.xbox_StickLeftClick,
                    SteamVR_Actions.xbox_StickRightClick};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[]
            {
                    SteamVR_Actions.xbox_Vibration};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[]
            {
                    SteamVR_Actions.xbox_Vibration};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[0];
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[]
            {
                    SteamVR_Actions.xbox_A,
                    SteamVR_Actions.xbox_B,
                    SteamVR_Actions.xbox_Y,
                    SteamVR_Actions.xbox_X,
                    SteamVR_Actions.xbox_Start,
                    SteamVR_Actions.xbox_Select,
                    SteamVR_Actions.xbox_DUp,
                    SteamVR_Actions.xbox_DDown,
                    SteamVR_Actions.xbox_DLeft,
                    SteamVR_Actions.xbox_DRight,
                    SteamVR_Actions.xbox_LB,
                    SteamVR_Actions.xbox_RB,
                    SteamVR_Actions.xbox_StickLeftClick,
                    SteamVR_Actions.xbox_StickRightClick};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[]
            {
                    SteamVR_Actions.xbox_LT,
                    SteamVR_Actions.xbox_RT};
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[]
            {
                    SteamVR_Actions.xbox_DPad,
                    SteamVR_Actions.xbox_StickLeft,
                    SteamVR_Actions.xbox_StickRight};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[0];
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[]
            {
                    SteamVR_Actions.xbox_A,
                    SteamVR_Actions.xbox_B,
                    SteamVR_Actions.xbox_Y,
                    SteamVR_Actions.xbox_X,
                    SteamVR_Actions.xbox_Start,
                    SteamVR_Actions.xbox_Select,
                    SteamVR_Actions.xbox_DUp,
                    SteamVR_Actions.xbox_DDown,
                    SteamVR_Actions.xbox_DLeft,
                    SteamVR_Actions.xbox_DRight,
                    SteamVR_Actions.xbox_DPad,
                    SteamVR_Actions.xbox_StickLeft,
                    SteamVR_Actions.xbox_StickRight,
                    SteamVR_Actions.xbox_LB,
                    SteamVR_Actions.xbox_RB,
                    SteamVR_Actions.xbox_LT,
                    SteamVR_Actions.xbox_RT,
                    SteamVR_Actions.xbox_StickLeftClick,
                    SteamVR_Actions.xbox_StickRightClick};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_xbox_A = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/Xbox/in/A")));
            SteamVR_Actions.p_xbox_B = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/Xbox/in/B")));
            SteamVR_Actions.p_xbox_Y = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/Xbox/in/Y")));
            SteamVR_Actions.p_xbox_X = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/Xbox/in/X")));
            SteamVR_Actions.p_xbox_Start = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/Xbox/in/Start")));
            SteamVR_Actions.p_xbox_Select = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/Xbox/in/Select")));
            SteamVR_Actions.p_xbox_DUp = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/Xbox/in/DUp")));
            SteamVR_Actions.p_xbox_DDown = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/Xbox/in/DDown")));
            SteamVR_Actions.p_xbox_DLeft = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/Xbox/in/DLeft")));
            SteamVR_Actions.p_xbox_DRight = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/Xbox/in/DRight")));
            SteamVR_Actions.p_xbox_DPad = ((SteamVR_Action_Vector2)(SteamVR_Action.Create <SteamVR_Action_Vector2>("/actions/Xbox/in/DPad")));
            SteamVR_Actions.p_xbox_StickLeft = ((SteamVR_Action_Vector2)(SteamVR_Action.Create <SteamVR_Action_Vector2>("/actions/Xbox/in/StickLeft")));
            SteamVR_Actions.p_xbox_StickRight = ((SteamVR_Action_Vector2)(SteamVR_Action.Create <SteamVR_Action_Vector2>("/actions/Xbox/in/StickRight")));
            SteamVR_Actions.p_xbox_LB = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/Xbox/in/LB")));
            SteamVR_Actions.p_xbox_RB = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/Xbox/in/RB")));
            SteamVR_Actions.p_xbox_LT = ((SteamVR_Action_Single)(SteamVR_Action.Create <SteamVR_Action_Single>("/actions/Xbox/in/LT")));
            SteamVR_Actions.p_xbox_RT = ((SteamVR_Action_Single)(SteamVR_Action.Create <SteamVR_Action_Single>("/actions/Xbox/in/RT")));
            SteamVR_Actions.p_xbox_StickLeftClick = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/Xbox/in/StickLeftClick")));
            SteamVR_Actions.p_xbox_StickRightClick = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/Xbox/in/StickRightClick")));
            SteamVR_Actions.p_xbox_Vibration = ((SteamVR_Action_Vibration)(SteamVR_Action.Create <SteamVR_Action_Vibration>("/actions/Xbox/out/Vibration")));
        }
    }
}
